-- QUESTION 1
-- SELECT *
-- FROM cd.facilities;
-- QUESTION 2
-- SELECT name,membercost
-- FROM cd.facilities;
-- QUESTION 3
-- SELECT name
-- FROM cd.facilities
-- WHERE membercost > 0;
-- QUESTION 4
-- SELECT facid,
-- name,
-- membercost,
-- monthlymaintenance
-- FROM cd.facilities
-- WHERE membercost > 0
-- AND membercost < monthlymaintenance/50;
-- QUESTION 5
-- SELECT name
-- FROM cd.facilities
-- WHERE name LIKE '%Tennis%';
-- QUESTION 6
-- SELECT *
-- FROM cd.facilities
-- WHERE facid IN (1,5);
-- QUESTION 7
-- SELECT memid,
-- surname,
-- firstname,
-- joindate
-- FROM cd.members
-- WHERE joindate >= '2012-09-01';
-- QUESTION 8
-- SELECT DISTINCT surname
-- FROM cd.members
-- ORDER BY surname
-- LIMIT 10;
-- QUESTION 9
-- SELECT max(joindate) AS latest
-- FROM cd.members;
-- QUESTION 10
-- SELECT COUNT(*) 
-- FROM cd.facilities
-- WHERE guestcost >= 10;
-- QUESTION 12
-- SELECT facid,SUM(slots) AS total_slots 
-- FROM cd.bookings
-- WHERE starttime >= '2012-09-01'
-- AND starttime < '2012-10-01'
-- GROUP BY facid
-- ORDER BY total_slots;
-- QUESTION 13
-- SELECT facid,SUM(slots) AS total_slots 
-- FROM cd.bookings
-- GROUP BY facid
-- HAVING SUM(slots) > 1000
-- ORDER BY facid;
-- QUESTION 14
-- SELECT name,starttime
-- FROM cd.facilities AS fac
-- JOIN cd.bookings AS bks 
-- ON fac.facid = bks.facid
-- WHERE fac.facid IN (0,1)
-- AND starttime >= '2012-09-21' AND starttime < '2012-09-22'
-- ORDER BY starttime;
-- QUESTION 15
SELECT starttime 
FROM cd.members AS mem
JOIN cd.bookings AS bks 
ON bks.memid = mem.memid
WHERE firstname = 'David'
AND surname = 'Farrell';