-- CREATE TABLE students(
-- 	student_id serial PRIMARY KEY,
-- 	first_name VARCHAR(45) NOT NULL,
-- 	last_name VARCHAR(45) NOT NULL,
-- 	homeroom_number integer,
-- 	phone VARCHAR(20) UNIQUE NOT NULL,
-- 	email VARCHAR(20) UNIQUE,
-- 	grad_year integer 
-- );
-- CREATE TABLE teachers(
-- 	teacher_id serial PRIMARY KEY,
-- 	first_name VARCHAR(45) NOT NULL,
-- 	last_name VARCHAR(45) NOT NULL,
-- 	homeroom_number integer,
-- 	department VARCHAR(45),
-- 	email VARCHAR(20) UNIQUE,
-- 	phone VARCHAR(20) UNIQUE
-- );
-- INSERT INTO students(first_name,last_name,homeroom_number,phone,grad_year)
-- VALUES ('Mark','Watney',5,7775551234,2035);
INSERT INTO teachers(first_name,last_name,homeroom_number,department,email,phone)
VALUES ('Jonas','Salk',5,'Biology','jsalk@school.org',7775554321);