-- CREATE TABLE test_two (
-- 	test_id serial PRIMARY KEY	
-- );
-- DROP TABLE test_two;
-- DROP TABLE test_two; -- WILL RETURN ERROR
-- DROP TABLE IF EXISTS test_two; -- WILL RETURN NOTICE
DROP TABLE IF EXISTS test_two RESTRICT; -- REFUSE DROP IF DEPENDENT OBJECT EXIST
DROP TABLE IF EXISTS test_two CASCADE; -- FORCE DROP DEPENDENT OBJECT (VIEWS) TABLE