-- UPDATE link
-- SET description = 'Empty Description';
-- UPDATE link
-- SET description = 'Name starts with A'
-- WHERE name LIKE 'A%';
-- UPDATE link
-- SET description = name;
-- UPDATE link
-- SET description = 'New Description'
-- WHERE id = 1
-- RETURNING id,url,name,description; --RETURN UPDATED COLUMNS